apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-solucao-ddd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minha-solucao-ddd
  template:
    metadata:
      labels:
        app: minha-solucao-ddd
    spec:
      containers:
      - name: minha-solucao-ddd
        image: moacirpfau719/minha-solucao-ddd:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: minha-solucao-ddd-service
spec:
  selector:
    app: minha-solucao-ddd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minha-solucao-ddd-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: minha-solucao.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minha-solucao-ddd-service
            port:
              number: 80
