apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-aplicacao-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minha-aplicacao
  template:
    metadata:
      labels:
        app: minha-aplicacao
    spec:
      containers:
      - name: minha-aplicacao
        image: minha-aplicacao:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: minha-aplicacao-service
spec:
  selector:
    app: minha-aplicacao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
